<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>stockroom-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Stockroom.Application/Stockroom.Application.csproj" />
    <ProjectReference Include="../Stockroom.Infrastructure/Stockroom.Infrastructure.csproj" />
  </ItemGroup>
</Project>
